---
abstract: 'Define your own method resolution order'
author:
  - 'Florian Ragwitz <rafl@debian.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Variable::Magic: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.90'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MRO-Define
no_index:
  directory:
    - inc
    - t
requires:
  XSLoader: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
